import Head from 'next/head';
import {getPostsForTopPage, getAllTags} from '../lib/notionAPI';
import SinglePost from '../components/Post/SinglePost';
import { GetStaticProps } from 'next';
import Link from 'next/link';
import Tag from '../components/Tag/Tag';

export const getStaticProps: GetStaticProps = async () => {
  const fourPosts = await getPostsForTopPage(4);
  const allTags = await getAllTags();
  return {
    props: {
      fourPosts,
      allTags,
    },
    revalidate: 60 * 60,
  };
};

export default function Home({ fourPosts, allTags }) {
  return (
    <div className='container h-full w-full mx-auto font-mono'>
      <Head>
        <title>Notion Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main className="container w-full mt-16">
      <h1 className='text-5xl font-medium text-center mb-16'>Notion Blog</h1>
      {fourPosts.map((post) => (
        <div key={post.id} className='mx-4'>
          <SinglePost
            id = {post.id}
            title = {post.title}
            description = {post.description}
            date={post.date}
            tags={post.tags}
            slug={post.slug}
						isPaginationPage={false}
          />
        </div>
      ))}
      <div className='flex justify-center my-6'>
      <Link href="/posts/page/1" className='py-2 px-6 block rounded-md bg-sky-900 text-white'>
        もっと見る
      </Link>
      </div>
      <Tag tags={allTags} />
    </main>

    </div>
  )
}
